#' Reads in data.
#'
#' This function reads in data generated by the US National Highway Traffic
#' Safety Administration's Fatality Analysis Reporting System.
#'
#' @param filename location or name of the file to be read in
#'
#' @return This function returns the data formatted in data frame table
#'
#' @note If the data you are trying to pass doesn't exist in that location or is
#' incorrectly spell, function will return an error.
#'
#' @importFrom ("readr", "read_csv")
#' @importFrom ("dplyr", "tbl_df")
#'
#' @examples
#' \dontrun{
#' fars_read('courseraPack/accident_2013.csv.brz')
#' }

fars_read <- function(filename) {
  if(!file.exists(filename))
    stop("file '", filename, "' does not exist")
  data <- suppressMessages({
    readr::read_csv(filename, progress = FALSE)
  })
  dplyr::tbl_df(data)
}
